jco.server.gwhost=HECCDEV.HAVELLS.COM
jco.server.gwserv=3300
jco.server.progid=DOTVIKMW
jco.server.connection_count=10
jco.server.trace=8
jco.server.repository_destination=HAVELLS_ECC_DEV

# jco.server.saprouter=
# jco.server.max_startup_delay=
# jco.server.repository_destination=
# jco.server.repository_map
# jco.server.worker_thread_count
# jco.server.worker_thread_min_count