#Property of the Adapter as SAP
#Property use for the connection number in cptsapidexnumber column  from sapcpt table 
sapidexnumber=3

#Property for the SAP
DEFAULT_DATE_FORMAT_SAP = yyyy-MM-dd
DEFAULT_DATE_FORMAT_HF = dd-MM-yyyy
DEFAULT_TIME_FORMAT_SAP = yyyy-MM-dd
DEFAULT_TIME_FORMAT_HF = dd-MM-yyyy
DEFAULT_LOCALE=en

sapidex.for.roundrobin=3:HAVELLS_ECC_PROD$2:HAVELLS_ECC_QA$1:HAVELLS_ECC_DEV
sapidex.mapto.function=1:HAVELLS_ECC_DEV$2:HAVELLS_ECC_QA$3:HAVELLS_ECC_PROD


LDAP_PROVIDER_URL=ldap://10.101.2.155:389
LOTUS_TRAVELER_AUTH_URL=http://traveler.havells.com/servlet/traveler


v2retail.enable.acl=1
