major.version.1.Android=2
minor.version.1.Android=1
download.url.1.Android=http://mkonnect.havells.com:7081/xmwcshavells/wap/builds/android/EmployeeMKonnect.apk
major.version.com.havells.mKonnect.iPhone=4
minor.version.com.havells.mKonnect.iPhone=0
download.url.com.havells.mKonnect.iPhone=https://mkonnect.havells.com:9443/xmwcshavells/wap/builds/iPhone/XMWClient.html

