# mail.smtp.host=10.101.2.158
mail.smtp.host=smtp.havells.com
mail.transport.protocol = smtp
mail.debug = true
mail.smtp.auth = false
mail.smtp.port = 2521
sender.username = mKonnect@havells.com
sender.password = mKonnect
is.ssl.class=0
log_subject="Middleware log"
subject.forgetpass = New Password
subject.expirepass = New Password
body_forgetpass = Your Password is Reset. New Password is 

body_expirepass = Your Password is Reset. New Password is 
client.msg.forgetpass = Your password is changed and new password is send to your mail
client.msg.expirepass = Your password is expire and new password is send to your mail

defaultSapInstanceId = HAVELLS_ECC_PROD
defaultCrmSapInstanceId = HAVELLS_CRM_NEW_PROD
webtel.Authorization.key=Authorization 
webtel.Authorization.value=Authorization /IalkRmh3z4=:::ZH4TUvIeJ3A=

oyo.Authorization.key=ACCESS_TOKEN
oyo.Authorization.value=SGFoMzg5b2c2bnYycXNZZGNmWEQ6QWs1d2tKdFpQckJ4UDR6V3V4Q2c=

#con.setConnectTimeout=10*60*60*1000
con.setReadTimeout=60000
