xml.path = D://Dotvik//xmwgateway//xsgml
lang.support.table = Xmwfmm$Mdmpvm
mwadminstr = dotvik@sol\#901
clientsessionexpiretime=1800000
#clientsessionexpiretime=60000
invalidnetworkrequest = Invalid Network Request, Please send correct network request
networkerror=Network error on Server,Please try again!
sessionexpiremsg=Session is expired please login again ! 

is.enable.device.auth=1
device.register.message=Your device is not registered , Please ask admin to add your device with number 
is.auto.register.device=1
xmw.passthrough.token=1

msg.exception.client.json.parse = Error Send the correct data to submit!
msg.exception.client.service.unavailable = Requested Service is not available!
msg.exception.client.session.expire = Your Session expired , Please Login Again!
msg.exception.client.password.reset = Password is reset by Administrator , Please change your password!
msg.exception.client.other = Your application getting other error!

msg.exception.xmw.platform.hibernate = Error in the Hibernate exception!
msg.exception.xmw.platform.other = Network error on Server,Please try again!

msg.exception.adapter.adapter.connection = Sap Server is down, Please try Again !
msg.exception.adapter.data.parse = Data is parse to the adapter is not submit!
msg.exception.adapter.other = There are some error in the sap server !
traveler.url=http://10.101.2.171/servlet/traveler
user.agent.havells=bb10$android$iphone$ipad

sap.serverdown=1
serverdown.time.from=06-06-2015 17:00:00
serverdown.time.to=08-06-2015 08:00:00