app.search.detail = SBC:[Search By Code]$SBN:[Search By Name]

#For the property of ESS Application 
app.flow.xess=authorization:[1]$menu:[1]$master:[1]$search:[0]$xml:[1]$menu_operation_support:[0]$xml_report:[1]$xml_form:[1]
app.authorization.xess=is_auth_by_pass:[0]$auth_on_adapter:[SAP]
app.role.xess=role_response_from_adapter:[0]$default_role:[ESS_USER]$is_use_only_default:[1]
app.login.other.property.xess=
app.xml.update.version.xess=1


#For the property of Sales app 
app.flow.xsales=authorization:[1]$menu:[1]$master:[1]$search:[1]$xml:[1]$menu_operation_support:[0]$xml_report:[1]$xml_form:[1]
app.authorization.xsales=is_auth_by_pass:[1]$auth_on_adapter:[SAP]
app.role.xsales=role_response_from_adapter:[0]$default_role:[SALES_USER]$is_use_only_default:[1]
app.login.other.property.xsales=
app.xml.update.version.xsales=1
app.search.type.xsales=SBC$SBN$detail:[SBC:Search By Code$SBN:Search By Name]

#For the property of Workflow app 
app.flow.xwf=authorization:[1]$menu:[1]$master:[0]$search:[0]$xml:[1]$menu_operation_support:[0]$xml_report:[1]$xml_form:[0]
app.authorization.xwf=is_auth_by_pass:[0]$auth_on_adapter:[SAP]
app.role.xwf=role_response_from_adapter:[0]$default_role:[WF_USER]$is_use_only_default:[1]
app.login.other.property.xwf=call_name:[FOR_REPORT]$adapter_type:[SAP]$adapter_id=[SAP_ADPTER_1]
app.search.detail.xwf=type:[SBC$SBN]$detail:[SBC:[Search By Code]$SBN:[Search By Name]]
app.xml.update.version.xwf=1

#For the property of powerplus app 
app.flow.xpowerplus=authorization:[1]$menu:[1]$master:[1]$search:[0]$xml:[1]$menu_operation_support:[0]$xml_report:[1]$xml_form:[1]
app.authorization.xpowerplus=is_auth_by_pass:[1]$auth_on_adapter:[SAP]
app.role.xpowerplus=role_response_from_adapter:[0]$default_role:[POWERPLUS_USER]$is_use_only_default:[1]
app.login.other.property.xpowerplus=

app.xml.update.version.xpowerplus=1

# Application dependency detail
app.dependencyapps.is.depend.xess = 0
app.dependencyapps.is.depend.xsales = 1
app.dependencyapps.is.depend.xwf = 1
app.dependencyapps.detail.xwf = xess
app.dependencyapps.detail.xsales = xess
app.dependencyapps.detail.xpowerplus= xess
app.dependencyapps.is.depend.xpowerplus= 1


# MW, SAP , WEBSERVICES,ORACLEAPPS
isresourcedump=true
hibernate_tableplace=
isnewhibernatetableadded=true






